<?php

namespace AppBundle\Repository;

/**
 * ProblemMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemMessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProblemByLocationId($locationId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT * FROM problem_message'.
                ' WHERE id ='. $locationId
            )
            ->getResult();
    }
}
