<?php

namespace AppBundle\Repository;

/**
 * StatusMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
